spring:
  profiles:
    active: test
---

server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/course-project
    username: postgres
    password: postgres
---

server:
  port: 8081
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/course-project-test}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
---

server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod