name: Build

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Declare some variables
#        shell: bash
#        run: |
#          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
#          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#      - name: Build Docker image
#        run: ./gradlew bootBuildImage

#      - name: Configure AWS credentials
#        id: creds
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/my-github-actions-role
#          aws-region: eu-central-1
#          output-credentials: true
#
#      - name: Login to AWS ECR
#        run: |
#          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com
#
#      - name: Tag Docker image
#        run: docker tag fitness-app-image:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/fitness-app-repo:latest
#
#      - name: Push Docker image to AWS ECR
#        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/fitness-app-repo:latest
#
#      - name: Upload Dockerrun.aws.json file to AWS Elastic Beanstalk
#        uses: einaregilsson/beanstalk-deploy@v21
#        with:
#          aws_access_key: ${{ steps.creds.outputs.aws-access-key-id }}
#          aws_secret_key: ${{ steps.creds.outputs.aws-secret-access-key }}
#          region: eu-central-1
#          application_name: d-fitness
#          environment_name: D-fitness-env-docker
#          version_label: ${{ env.branch }}.${{ env.sha_short }}
#          deployment_package: Dockerrun.aws.json